### ISSUE TITLE
Formulae that have been renamed should be handed better

### ISSUE THREAD

**Issue by technicalpickles** [Homebrew/homebrew-bundle#176] opened 2016-05-16 22:32 UTC
`brew bundle check` was introduced over in https://github.com/Homebrew/homebrew-bundle/issues/100 , and we use it a `script/bootstrap` script like:

```shell
  brew update >/dev/null
  brew bundle check &>/dev/null || brew bundle
```

Ideally, `brew bundle` if anything isn't installed, but I ran into a project that was triggering `brew bundle` every run of `bootstrap`. To try to identify why, I started making changes to `lib/bundle/commands/check.rb` to try to figure out what specifically was triggering it. I'll follow up with a PR when I can, but I found the thing that was causing `brew bundle check` to return false:

```
$ brew bundle check --verbose
brew bundle can't satisfy your Brewfile's dependencies.
Install missing dependencies with `brew bundle install`.

Formulae to install:
- heroku-toolbelt
Kernel.exit
Error: Kernel.exit

$ brew install heroku-toolbelt
Warning: heroku-toolbelt already installed, it's just not migrated
You can migrate formula with `brew migrate heroku`
Or you can force install it with `brew install heroku --force`
```

I am able to fix this on my machine by running `brew unlink heroku-toolbelt; brew install heroku --force`, and updating `Brewfile` to use `heroku` instead of `heroku-toolbelt`. However, I'm worried about others using this project not being able to see the information they need to fix their environment.

I did try reproducing this with installing herokut-toolbelt, but wasn't quite able to get it to fail in the same way.

**Comment by mikemcquaid** [comment] 2016-05-17 07:06
Migrations are done by `brew update`. Can you try to check out an old version of `Library/Taps/Homebrew/homebrew-core` before the `heroku` rename, install `heroku-toolbelt`, and then run the `script/bootstrap` again and see if you can reproduce?

**Comment by MikeMcQuaid** [comment] 2016-06-03 13:16
> Can you try to check out an old version of Library/Taps/Homebrew/homebrew-core before the heroku rename, install heroku-toolbelt, and then run the script/bootstrap again and see if you can reproduce?

@technicalpickles Gentle ping on this, thanks.

**Comment by technicalpickles** [comment] 2016-06-03 14:55
The rename commit is https://github.com/Homebrew/homebrew-core/commit/11432e047c3373497fb12285190dc0d5fbe597df so I checked out it's parent. `brew uninstall heroku; brew uninstall heroku-toolbelt` to get to a clean slate, then `brew install heroku-toolbelt`. I ran `brew update` and saw among other things:

```
==> Migrating heroku-toolbelt to heroku
==> Unlinking heroku-toolbelt
Moving to: /usr/local/Cellar/heroku
==> Linking heroku
```

I get the same result when doing `brew bundle check --verbose`:

```
$ brew bundle check --verbose
brew bundle can't satisfy your Brewfile's dependencies.
Install missing dependencies with `brew bundle install`.

Formulae to install:
- heroku-toolbelt
Kernel.exit
Error: Kernel.exit
```

**Comment by technicalpickles** [comment] 2016-06-03 15:25
I think the title can be updated to like "formula in Brewfile that has since been renamed and migrated not fixed by brew bundle"

**Comment by MikeMcQuaid** [comment] 2016-06-04 14:09
@technicalpickles Yeh. We'll likely throw an error because it's not `homebrew-bundle`'s responsibility but could throw a better one.

**Comment by MikeMcQuaid** [comment] 2016-07-20 22:54
Going to close this out but will consider a fix if we get a few more reports here.

**Closed by MikeMcQuaid** 2016-07-20 22:54 UTC

**Comment by technicalpickles** [comment] 2016-10-13 19:45
I ran into this on another project I work on. It was the same dependency causing a problem, ie `heroku-toolbelt` being renamed to `heroku`.

**Comment by darkn3rd** [comment] 2017-11-13 19:12
I am running into kernel.exit consistently with this Brewfile:

```ruby
cask_args appdir: '/Applications'
cask 'virtualbox'
cask 'virtualbox-extension-pack'
cask 'vagrant'
cask 'vagrant-manager'
cask 'docker-toolbox'

tap 'homebrew/completions/'
brew 'docker-machine-completion'
brew 'docker-completion'
brew 'docker-compose-completion'
brew 'vagrant-completion'
```
