### ISSUE TITLE
No file found firefox.rb

### ISSUE THREAD

**Issue by crazytaxi824** [Homebrew/homebrew-bundle#1168] opened 2023-02-16 10:44 UTC
Error: No file found at https://raw.githubusercontent.com/Homebrew/homebrew-cask/cc58401c0905753619a9fc12dc733518beb75b05/Casks/firefox.rb

**Comment by SMillerDev** [comment] 2023-02-16 10:45
Duplicate of https://github.com/Homebrew/homebrew-cask/issues/141436

**Closed** 2023-02-16 10:47 UTC
